### PR TITLE
Update port names and numbers for insecure mode

### PR DESCRIPTION
**Pull request by travisgroth**
Closes https://github.com/pomerium/pomerium-helm/issues/88

When using insecure mode, change port names and numbers.  While mostly cosmetic, this can assist ingress controllers and service mesh systems detect correct protocols automatically.

### CODE REVIEW

**Comment by Vad1mo** [comment]
the services are still http + port 443

See this example:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: pomerium-proxy
  namespace: pomerium
  selfLink: /api/v1/namespaces/pomerium/services/pomerium-proxy
  uid: dd6a4567-cb3b-4161-b953-7614e406f3e7
  resourceVersion: '16537130911'
  creationTimestamp: '2020-05-15T06:19:47Z'
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pomerium-proxy
    helm.sh/chart: pomerium-9.1.0
  annotations:
    meta.helm.sh/release-name: pomerium
    meta.helm.sh/release-namespace: pomerium
spec:
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: http
```

**Comment by travisgroth** [comment]
Ah.  I forgot to mention this.  

The external service port is still defined explicitly by `service.externalPort`.  Try setting `service.externalPort` to `80`.

I'll see about making that default dynamic.  For now we're just relying on the explicit option.

**Comment by travisgroth** [comment]
Actually, I think I have it.  Try again with just `insecure`.

**Comment by Vad1mo** [comment]
@travisgroth tested your new code. It works as expected.

**Comment by travisgroth** [comment]
> Maybe a readme update is needed:
> 
> The default value in `service.externalPort` should be `80` or `443` depending on `config.insecure`= `false` or `true`

Yep agreed.  I wanted to confirm before updating docs.  Thanks for testing!

**Pull request merged**
