### PR TITLE
update to v2 since the redis subchart requires v2

### PR DESCRIPTION
**Pull request by nicgrayson**
## Summary
The redis subchart is set to v2 so you should bump this chart to v2

### CODE REVIEW

**Comment by travisgroth** [comment]
@nicgrayson I think that is a holdover from helm2 support.  We can probably drop that at this point.

Would you mind:

* bumping the major number
* update change log reflecting drop of helm 2 support
* moving dependencies to `Chart.yaml`

Thanks!

**Comment by nicgrayson** [comment]
@travisgroth done and done

**Review by travisgroth — CHANGES_REQUESTED** [review]
Minor typo.  

Could you move the contents of `requirements.yaml` and `requirements.lock` into `Chart.yaml` and `Chart.lock` respectively?  That will put us into full compliance with api `v2`.

**Comment by nicgrayson** [comment]
@travisgroth I think I got those updated correctly. Do you want to upgrade the redis chart? Looks like it's old.

**Comment by travisgroth** [comment]
> @travisgroth I think I got those updated correctly. 

I think the `lock` data needs to be migrated too.

> Do you want to upgrade the redis chart? Looks like it's old.

Not against it - the upstream changelog needs a review to see if there's any compatibility problems.  I think they're two major versions ahead now.

**Comment by nicgrayson** [comment]
Not sure why this closed. I've updated the PR with version 18 and the needed chart.lock file.

**Comment by travisgroth** [comment]
FYI added a version bump to address https://github.com/bitnami/charts/issues/5033

**Review by travisgroth — APPROVED** [review]

**Pull request merged**
