### PR TITLE
add conditional to metrics port

### PR DESCRIPTION
**Pull request by ThomasEhling**
## Summary
When settings the variable metrics.enabled to false, the metrics are not exposed but the service port is still exposed.
It is not coherent and can be a security threat.

## Related issues
metrics port should not be exposed if the functionality is disabled #322: 
 https://github.com/pomerium/pomerium-helm/issues/322

**Checklist**:
- [x] add related issues
- [x] update Configuration in README --> no need,  metrics.enabled  already says -> Enable prometheus metrics endpoint
- [ ] update Changelog in README (major versions)
- [ ] update Upgrading in README (breaking changes)
- [x] ready for review

### CODE REVIEW

**Review by desimone — APPROVED** [review]
Sounds reasonable to me.

**Comment by desimone** [comment]
Thanks for the contribution. @ThomasEhling 

\cc @wasaga

**Comment by desimone** [comment]
Looks like a version bump is needed. 

>  ✖︎ pomerium => (version: "32.0.3", path: "charts/pomerium") > Chart version not ok. Needs a version bump!

**Comment by ThomasEhling** [comment]
@desimone 
Thanks ! I updated the pomerium version to 32.0.4

**Review by calebdoxsey — DISMISSED** [review]

**Comment by ThomasEhling** [comment]
@calebdoxsey 
pomerium version updated to 32.0.5

**Comment by ThomasEhling** [comment]
Hi @desimone and @calebdoxsey !
Any update on this PR ?

**Review by desimone — APPROVED** [review]

**Comment by desimone** [comment]
Thanks for bumping the version @ThomasEhling , LGTM.

**Pull request merged**
